# SPDX-FileCopyrightText: 2025 Pagefault Games
# SPDX-FileContributor: SirzBenjie
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

[[annotations]]
path = "go.sum"
SPDX-FileCopyrightText = "CC0-1.0"
SPDX-License-Identifier = "CC0-1.0"